---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-controller
rules:
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - "roles"
    - "clusterroles"
  verbs:
    - "bind"
    - "escalate"
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - "clusterrolebindings"
    - "rolebindings"
  verbs:
    - "create"
- apiGroups:
    - "k8s.kudo.dev"
  resources:
    - "escalationpolicies"
    - "escalations"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "k8s.kudo.dev"
  resources:
    - "escalations/status"
  verbs:
    - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{ default .Release.namespace "default" }}
roleRef:
  kind: ClusterRole
  name: {{ include "helm.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
