---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-viewer
rules:
- apiGroups:
   - ""
  resources:
    - "configmaps"
  verbs:
    - "get"
    - "list"
    - "watch"
---
apiVersion: v1
kind: Namespace
metadata:
  name: some-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: some-app
data:
  some: "data"
