---
apiVersion: k8s.kudo.dev/v1alpha1
kind: EscalationPolicy
metadata:
  name: rbac-escalation-policy-example
spec:
  subjects: # (required) who has the right to trigger this escalation.
    - kind: Group
      name: kudo-test-group
  challenges: # (optional) list of challenges being applied when esclating.
    - kind: TwoFactor
      reviewers:
        - kind: Group
          name: squad-b@voiapp.io
  target: # (required) what the escalation grants
    duration: 70s
    grants:
    - kind: KubernetesRoleBinding
      defaultNamespace: some-app
      allowedNamespaces:
        - some-app
        - some-other-app
      roleRef:
        kind: ClusterRole
        name: config-viewer
        apiGroup: rbac.authorization.k8s.io
