---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: can-escalate
rules:
- apiGroups:
    - "k8s.kudo.dev"
  resources:
    - "escalations"
  verbs:
    - "create"
    - "get"
    - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: can-escalate
subjects:
- kind: Group
  name: kudo-test-group
roleRef:
  kind: ClusterRole
  name: can-escalate
  apiGroup: rbac.authorization.k8s.io
