---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: escalations.k8s.kudo.dev
spec:
  group: k8s.kudo.dev
  scope: Cluster
  names:
    plural: escalations
    singular: escalation
    kind: Escalation
    shortNames:
    - esc
  versions:
    - name:    v1alpha1
      served:  true
      storage: true
      subresources:
          status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policyName:
                  type: string
                requestor:
                  type: string
                reason:
                  type: string
                namespace:
                  type: string
              required:
                - policyName
                - reason
            status:
              type: object
              properties:
                state:
                  type: string
                stateDetails:
                  type: string
                policyUid:
                  type: string
                policyVersion:
                  type: string
                grantRefs:
                  type: array
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      uid:
                        type: string
                      resourceVersion:
                        type: string
                      status:
                        type: string

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
