---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: escalations.k8s.kudo.dev
spec:
  group: k8s.kudo.dev
  scope: Cluster
  names:
    plural: escalations
    singular: escalation
    kind: Escalation
    shortNames:
    - esc
  versions:
    - name:    v1alpha1
      served:  true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policyName:
                  type: string
                submittedBy:
                  type: string
                reason:
                  type: string
              required:
                - policyName
                - reason
