name: ci
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: true
      - name: Install Dependencies
        run: make install_dependencies
      - name: Check Code Generation
        run: make check_codegen
        env:
          GOPATH: /home/runner/go
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          args: --timeout 5m
      - name: Run Unit Tests
        run: make unit_tests

  e2e-tests:
    name: e2e Test Suite
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: true
      - name: Install google/ko
        uses: imjasonh/setup-ko@v0.4
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.3
      - name: Install k3d
        uses: rinx/setup-k3d@v0.0.4
        with:
          version: v5.4.4
          skipClusterCreation: true
      - name: Patch /etc/hosts
        run: |
          echo "127.0.0.1 kudo-e2e-registry.localhost" | sudo tee -a /etc/hosts
      - name: Run The e2e Test Suite
        run: make e2e_tests

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - ci
    steps:
      - name: Release a New Version
        run: echo "do this when there's something to release!"
