---
name: Deploy Documentation Website
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install PostCSS CLI
        run: npm install -g postcss-cli
      - name: Install PostCSS and its deps
        run: npm install --save-dev autoprefixer postcss
        working-directory: ./docs
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.102.3'
          extended: true
      - name: Clean public directory
        run: rm -rf public
      - name: Build
        run: hugo  --minify -s ./docs
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
